version: '3.2'
services:
    db:
        image: postgres:latest
        container_name: springBootDB
        restart: always
        # ports:
        #     - 5432:5432
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
        volumes:
            - ./init_db:/docker-entrypoint-initdb.d
    java:
        image: openjdk:11
        container_name: springBoot
        restart: always
        ports:
            - 8080:8080
        tty: true
        stdin_open: true
        volumes: 
            - ./demopro:/usr/local/src/demopro
        depends_on:
            - db