# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
executors: 
  my-executor:
    docker:
      - image: cimg/openjdk:8.0
      - image: circleci/postgres:9.4
        environment:
          - POSTGRES_USER: postgres
          - POSTGRES_PASSWORD: postgres

jobs:
  build:
    executor:
      name: my-executor
          
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies
      - run: gradle build -x test

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - persist_to_workspace: 
          root: ~/repo
          paths: 
            - .
      # run tests!
      # - run: gradle test

      # - store_artifacts:
      #     path: ./build/reports
      #     destination: reports

      # - store_test_results:
      #     path: ./build/test-results
  
  test:
    executor:
      name: my-executor
    
    steps:
      - attach_workspace:
          at: ~/repo
      # run tests!
      - run: gradle test

      - store_artifacts:
          path: ./build/reports
          destination: reports

      - store_test_results:
          path: ./build/test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build