# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
executors: 
  my-executor:
    docker:
      - image: cimg/openjdk:8.0
        environment:
      # Customize the JVM maximum heap limit
          - JVM_OPTS: -Xmx3200m
          - TERM: dumb
          - GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      - image: circleci/postgres:9.4
        environment:
          - POSTGRES_USER: postgres
          - POSTGRES_PASSWORD: postgres

jobs:
  build:
    executor:
      name: my-executor
          
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout 
      # 依存関係をダウンロードしてキャッシュする
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "build.gradle" }}
          - v1-dependencies-{{ .Branch }}-
          - v1-dependencies-
      - run: gradle dependencies
      - run: gradle build -x test
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ .Branch }}-{{ checksum "build.gradle" }}
      # 他のjobでも共有する
      - persist_to_workspace: 
          root: ~/repo
          paths: 
            - .
  
  test:
    executor:
      name: my-executor
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      # run tests!
      - run: gradle test

      - store_artifacts:
          path: ./build/reports
          destination: reports

      - store_test_results:
          path: ./build/test-results

  deploy:
    executor:
      name: my-executor
    working_directory: ~/repo
    steps:
      - run:
          name: deploy mock
          command: echo deployed!!

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master